### PR TITLE
Added condition to match files correctly

### PR DESCRIPTION
**Pull request by crimx**
The plugin is trying to wrap all the files, which are not necessary the same format. Added `test` option for more control.

### CODE REVIEW

**Comment by ischyron** [comment]
this is a useful feature. I am using this.
helps with excluding css for ExtractTextPlugin

**Comment by ischyron** [comment]
is this repo abandoned ? @levp ?

**Comment by crimx** [comment]
@ischyron I think so. Try this <https://www.npmjs.com/package/wrapper-webpack-plugin2>.

**Comment by levp** [comment]
@ischyron @crimx It's not abandoned, I didn't know there's any interest in this.
I'll get to it shortly.

**Comment by levp** [comment]
@crimx @ischyron Pull request has been merged. 

@crimx Not sure what's the "GitHub" way of doing this, but I've made a few more commits editing your changes; mainly to avoid using ES6 features. I know the support is pretty good by now but I think the code is too small and simple to really need that.

I assume a `CONTRIBUTERS.md` file is needed now?

**Comment by crimx** [comment]
@levp Fine with me. Glad to see the project's back up and running.

**Pull request merged**
