### PR TITLE
Fix webpack 5 compatibility

### PR DESCRIPTION
**Pull request by AlexKlimenkov**
Fix for https://github.com/levp/wrapper-webpack-plugin/issues/15

### CODE REVIEW

**Comment by phoebusryan** [comment]
Please merge :)

**Comment by jdecked** [comment]
hey @levp, I build twitter.com and we're in the process of upgrading to webpack 5. this package is one of the last few things not supporting webpack 5 that we use, and we'd hate to have to maintain an internal fork of it 😢  would you do us a solid and review this PR plz? ty! 🙏

**Comment by i91** [comment]
We would really appreciate a merge, thanks @levp!

**Comment by Jojoshua** [comment]
Needing this also, please publish new beta

**Comment by wesgarland** [comment]
@levp please merge!

**Comment by levp** [comment]
Sorry for the totally unreasonable delay.

Published version 2.2.0 to npm which contains this fix.

**Comment by jdecked** [comment]
Woohoo, thanks @levp!

**Pull request merged**
